### PR TITLE
Remove MPS button, made MPS always show

### PR DESCRIPTION
**Pull request by whitephoenix0**
Is there a specific reason you are using python 2?
Also is there any way you could scrap the build and dist folders? I'm not real sure what they're for but they make cloning take a long time.

I think the next thing I'm going to do is change the buy buttons to include how many of each item you own "Thug" becomes "[23] Thug" etc.

### CODE REVIEW

**Comment by awkwardtechdude** [comment]
I really love these suggestions. I'm trying to keep working on the project,
though my team has gone on to some Unity work. If you want to help out with
the project, I can let you make edits. The build and dist directories were
an attempt to make binaries, but I guess most people interested would have
Python. Thanks for the help.

**Comment by whitephoenix0** [comment]
That would be great, though I'm not sure how much I would actually end up contributing.

**Comment by awkwardtechdude** [comment]
I have invited you. The pull you submitted did not run, though I don't think it ran anyway. I'll probably end up merging dev into master anyway.

**Comment by awkwardtechdude** [comment]
Fixed; parens were open

**Comment by awkwardtechdude** [comment]
I'll make the MPS count more prominent.

**Comment by whitephoenix0** [comment]
I didn't see any invites

**Comment by awkwardtechdude** [comment]
One is sent, I've made sure now.

**Pull request merged**
